CARS = [
    {
        "id": "honda_crv_hybrid_2026",
        "make": "Honda",
        "model": "CR-V",
        "year": 2026,
        "trim": "Hybrid Touring",
        "body_type": "SUV",
        "price_new": 42000,
        "price_used_avg": 35000,
        "fuel_type": "hybrid",
        "mpg_city": 43,
        "mpg_highway": 36,
        "seating_capacity": 5,
        "cargo_cu_ft": 39.3,
        "towing_capacity_lbs": 1500,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 9,
        "ground_clearance_in": 8.2,
        "turning_radius_ft": 18.7,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["wireless_carplay", "heated_seats", "hands_free_liftgate"],
        "best_for": ["family", "commute", "fuel_efficiency"],
        "image_url": "https://example.com/crv.jpg"
    },
    {
        "id": "toyota_sienna_2026",
        "make": "Toyota",
        "model": "Sienna",
        "year": 2026,
        "trim": "Platinum",
        "body_type": "minivan",
        "price_new": 55000,
        "price_used_avg": 42000,
        "fuel_type": "hybrid",
        "mpg_city": 36,
        "mpg_highway": 36,
        "seating_capacity": 8,
        "cargo_cu_ft": 101.0,
        "towing_capacity_lbs": 3500,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 9,
        "ground_clearance_in": 6.5,
        "turning_radius_ft": 19.5,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": True,
        "has_third_row": True,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["wireless_carplay", "heated_seats", "rear_entertainment"],
        "best_for": ["family", "cargo"],
        "image_url": "https://example.com/sienna.jpg"
    },
    {
        "id": "kia_telluride_2026",
        "make": "Kia",
        "model": "Telluride",
        "year": 2026,
        "trim": "SX Prestige",
        "body_type": "SUV",
        "price_new": 52000,
        "price_used_avg": 40000,
        "fuel_type": "gas",
        "mpg_city": 20,
        "mpg_highway": 26,
        "seating_capacity": 8,
        "cargo_cu_ft": 87.0,
        "towing_capacity_lbs": 5000,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 8,
        "ground_clearance_in": 8.0,
        "turning_radius_ft": 19.0,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": True,
        "has_third_row": True,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["wireless_carplay", "heated_seats", "panoramic_sunroof"],
        "best_for": ["family", "luxury"],
        "image_url": "https://example.com/telluride.jpg"
    },
    {
        "id": "subaru_ascent_2026",
        "make": "Subaru",
        "model": "Ascent",
        "year": 2026,
        "trim": "Touring",
        "body_type": "SUV",
        "price_new": 48000,
        "price_used_avg": 36000,
        "fuel_type": "gas",
        "mpg_city": 20,
        "mpg_highway": 26,
        "seating_capacity": 8,
        "cargo_cu_ft": 86.5,
        "towing_capacity_lbs": 5000,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 8,
        "ground_clearance_in": 8.7,
        "turning_radius_ft": 19.2,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": True,
        "has_third_row": True,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["starlink", "heated_seats", "blind_spot_monitoring"],
        "best_for": ["family", "safety"],
        "image_url": "https://example.com/ascent.jpg"
    },
    {
        "id": "toyota_camry_hybrid_2026",
        "make": "Toyota",
        "model": "Camry",
        "year": 2026,
        "trim": "XLE",
        "body_type": "sedan",
        "price_new": 34000,
        "price_used_avg": 26000,
        "fuel_type": "hybrid",
        "mpg_city": 51,
        "mpg_highway": 53,
        "seating_capacity": 5,
        "cargo_cu_ft": 15.1,
        "towing_capacity_lbs": 0,
        "drivetrain": "FWD",
        "safety_rating": 5,
        "reliability_score": 9,
        "ground_clearance_in": 5.7,
        "turning_radius_ft": 18.1,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["wireless_carplay", "heated_seats", "jbl_audio"],
        "best_for": ["commute", "fuel_efficiency"],
        "image_url": "https://example.com/camry.jpg"
    },
    {
        "id": "tesla_model_3_2026",
        "make": "Tesla",
        "model": "Model 3",
        "year": 2026,
        "trim": "Long Range",
        "body_type": "sedan",
        "price_new": 47000,
        "price_used_avg": 38000,
        "fuel_type": "electric",
        "mpg_city": 140,
        "mpg_highway": 125,
        "seating_capacity": 5,
        "cargo_cu_ft": 15.0,
        "towing_capacity_lbs": 0,
        "drivetrain": "RWD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 5.5,
        "turning_radius_ft": 18.5,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["autopilot", "heated_seats", "premium_audio"],
        "best_for": ["commute", "fuel_efficiency", "luxury"],
        "image_url": "https://example.com/model3.jpg"
    },
    {
        "id": "honda_accord_2026",
        "make": "Honda",
        "model": "Accord",
        "year": 2026,
        "trim": "Touring",
        "body_type": "sedan",
        "price_new": 38000,
        "price_used_avg": 29000,
        "fuel_type": "hybrid",
        "mpg_city": 48,
        "mpg_highway": 47,
        "seating_capacity": 5,
        "cargo_cu_ft": 16.7,
        "towing_capacity_lbs": 0,
        "drivetrain": "FWD",
        "safety_rating": 5,
        "reliability_score": 9,
        "ground_clearance_in": 5.8,
        "turning_radius_ft": 18.0,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["wireless_carplay", "heated_seats", "wireless_charging"],
        "best_for": ["commute", "fuel_efficiency"],
        "image_url": "https://example.com/accord.jpg"
    },
    {
        "id": "ford_bronco_2026",
        "make": "Ford",
        "model": "Bronco",
        "year": 2026,
        "trim": "Badlands",
        "body_type": "SUV",
        "price_new": 58000,
        "price_used_avg": 48000,
        "fuel_type": "gas",
        "mpg_city": 17,
        "mpg_highway": 21,
        "seating_capacity": 5,
        "cargo_cu_ft": 35.6,
        "towing_capacity_lbs": 4500,
        "drivetrain": "4WD",
        "safety_rating": 4,
        "reliability_score": 7,
        "ground_clearance_in": 11.6,
        "turning_radius_ft": 20.5,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": True,
        "is_manual_available": True,
        "key_features": ["removable_roof", "4x4_system", "offroad_tires"],
        "best_for": ["adventure", "off_road"],
        "image_url": "https://example.com/bronco.jpg"
    },
    {
        "id": "jeep_wrangler_2026",
        "make": "Jeep",
        "model": "Wrangler",
        "year": 2026,
        "trim": "Rubicon",
        "body_type": "SUV",
        "price_new": 52000,
        "price_used_avg": 42000,
        "fuel_type": "gas",
        "mpg_city": 17,
        "mpg_highway": 23,
        "seating_capacity": 5,
        "cargo_cu_ft": 31.7,
        "towing_capacity_lbs": 3500,
        "drivetrain": "4WD",
        "safety_rating": 4,
        "reliability_score": 6,
        "ground_clearance_in": 10.8,
        "turning_radius_ft": 18.6,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": True,
        "is_manual_available": True,
        "key_features": ["removable_top", "4x4_system", "rock_rails"],
        "best_for": ["adventure", "off_road"],
        "image_url": "https://example.com/wrangler.jpg"
    },
    {
        "id": "toyota_4runner_2026",
        "make": "Toyota",
        "model": "4Runner",
        "year": 2026,
        "trim": "TRD Pro",
        "body_type": "SUV",
        "price_new": 55000,
        "price_used_avg": 45000,
        "fuel_type": "gas",
        "mpg_city": 16,
        "mpg_highway": 19,
        "seating_capacity": 5,
        "cargo_cu_ft": 47.2,
        "towing_capacity_lbs": 5000,
        "drivetrain": "4WD",
        "safety_rating": 4,
        "reliability_score": 9,
        "ground_clearance_in": 9.6,
        "turning_radius_ft": 18.7,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["4x4_system", "skid_plates", "offroad_suspension"],
        "best_for": ["adventure", "off_road"],
        "image_url": "https://example.com/4runner.jpg"
    },
    {
        "id": "ford_f150_2026",
        "make": "Ford",
        "model": "F-150",
        "year": 2026,
        "trim": "Lariat",
        "body_type": "truck",
        "price_new": 65000,
        "price_used_avg": 52000,
        "fuel_type": "gas",
        "mpg_city": 18,
        "mpg_highway": 24,
        "seating_capacity": 6,
        "cargo_cu_ft": 52.8,
        "towing_capacity_lbs": 14000,
        "drivetrain": "4WD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 10.0,
        "turning_radius_ft": 21.0,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": True,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["pro_trailer_backup", "bed_utility", "towing_package"],
        "best_for": ["towing", "work"],
        "image_url": "https://example.com/f150.jpg"
    },
    {
        "id": "ram_1500_2026",
        "make": "Ram",
        "model": "1500",
        "year": 2026,
        "trim": "Limited",
        "body_type": "truck",
        "price_new": 70000,
        "price_used_avg": 55000,
        "fuel_type": "gas",
        "mpg_city": 17,
        "mpg_highway": 22,
        "seating_capacity": 6,
        "cargo_cu_ft": 53.9,
        "towing_capacity_lbs": 12950,
        "drivetrain": "4WD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 9.5,
        "turning_radius_ft": 20.8,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": True,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["air_suspension", "multifunction_tailgate", "premium_audio"],
        "best_for": ["towing", "luxury"],
        "image_url": "https://example.com/ram1500.jpg"
    },
    {
        "id": "toyota_tacoma_2026",
        "make": "Toyota",
        "model": "Tacoma",
        "year": 2026,
        "trim": "TRD Off-Road",
        "body_type": "truck",
        "price_new": 48000,
        "price_used_avg": 38000,
        "fuel_type": "gas",
        "mpg_city": 18,
        "mpg_highway": 22,
        "seating_capacity": 5,
        "cargo_cu_ft": 42.6,
        "towing_capacity_lbs": 6800,
        "drivetrain": "4WD",
        "safety_rating": 4,
        "reliability_score": 9,
        "ground_clearance_in": 9.4,
        "turning_radius_ft": 20.2,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": True,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["4x4_system", "offroad_suspension", "bed_utility"],
        "best_for": ["adventure", "towing"],
        "image_url": "https://example.com/tacoma.jpg"
    },
    {
        "id": "bmw_x5_2026",
        "make": "BMW",
        "model": "X5",
        "year": 2026,
        "trim": "xDrive40i",
        "body_type": "SUV",
        "price_new": 72000,
        "price_used_avg": 58000,
        "fuel_type": "gas",
        "mpg_city": 21,
        "mpg_highway": 25,
        "seating_capacity": 5,
        "cargo_cu_ft": 33.9,
        "towing_capacity_lbs": 6000,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 8.3,
        "turning_radius_ft": 19.8,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["harman_kardon", "hud", "gesture_control"],
        "best_for": ["luxury", "performance"],
        "image_url": "https://example.com/x5.jpg"
    },
    {
        "id": "mercedes_glc_2026",
        "make": "Mercedes-Benz",
        "model": "GLC",
        "year": 2026,
        "trim": "GLC 300",
        "body_type": "SUV",
        "price_new": 55000,
        "price_used_avg": 44000,
        "fuel_type": "gas",
        "mpg_city": 23,
        "mpg_highway": 30,
        "seating_capacity": 5,
        "cargo_cu_ft": 22.0,
        "towing_capacity_lbs": 3500,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 7.5,
        "turning_radius_ft": 18.5,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["burmester_audio", "mbux", "ambient_lighting"],
        "best_for": ["luxury", "commute"],
        "image_url": "https://example.com/glc.jpg"
    },
    {
        "id": "lexus_rx_2026",
        "make": "Lexus",
        "model": "RX",
        "year": 2026,
        "trim": "RX 450h+",
        "body_type": "SUV",
        "price_new": 58000,
        "price_used_avg": 46000,
        "fuel_type": "hybrid",
        "mpg_city": 38,
        "mpg_highway": 34,
        "seating_capacity": 5,
        "cargo_cu_ft": 29.6,
        "towing_capacity_lbs": 3500,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 9,
        "ground_clearance_in": 8.0,
        "turning_radius_ft": 18.9,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["mark_levinson", "panoramic_sunroof", "heated_ventilated_seats"],
        "best_for": ["luxury", "fuel_efficiency"],
        "image_url": "https://example.com/rx.jpg"
    },
    {
        "id": "hyundai_elantra_2026",
        "make": "Hyundai",
        "model": "Elantra",
        "year": 2026,
        "trim": "Limited",
        "body_type": "sedan",
        "price_new": 28000,
        "price_used_avg": 20000,
        "fuel_type": "gas",
        "mpg_city": 33,
        "mpg_highway": 41,
        "seating_capacity": 5,
        "cargo_cu_ft": 14.2,
        "towing_capacity_lbs": 0,
        "drivetrain": "FWD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 5.3,
        "turning_radius_ft": 17.7,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["wireless_carplay", "heated_seats", "sunroof"],
        "best_for": ["budget", "commute"],
        "image_url": "https://example.com/elantra.jpg"
    },
    {
        "id": "kia_soul_2026",
        "make": "Kia",
        "model": "Soul",
        "year": 2026,
        "trim": "X-Line",
        "body_type": "hatchback",
        "price_new": 25000,
        "price_used_avg": 18000,
        "fuel_type": "gas",
        "mpg_city": 28,
        "mpg_highway": 33,
        "seating_capacity": 5,
        "cargo_cu_ft": 24.2,
        "towing_capacity_lbs": 0,
        "drivetrain": "FWD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 6.7,
        "turning_radius_ft": 17.5,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["wireless_carplay", "heated_seats", "harman_kardon"],
        "best_for": ["budget", "city"],
        "image_url": "https://example.com/soul.jpg"
    },
    {
        "id": "nissan_versa_2026",
        "make": "Nissan",
        "model": "Versa",
        "year": 2026,
        "trim": "SR",
        "body_type": "sedan",
        "price_new": 22000,
        "price_used_avg": 15000,
        "fuel_type": "gas",
        "mpg_city": 32,
        "mpg_highway": 40,
        "seating_capacity": 5,
        "cargo_cu_ft": 14.7,
        "towing_capacity_lbs": 0,
        "drivetrain": "FWD",
        "safety_rating": 5,
        "reliability_score": 6,
        "ground_clearance_in": 5.2,
        "turning_radius_ft": 17.2,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["apple_carplay", "heated_seats", "remote_start"],
        "best_for": ["budget", "city"],
        "image_url": "https://example.com/versa.jpg"
    },
    {
        "id": "tesla_model_y_2026",
        "make": "Tesla",
        "model": "Model Y",
        "year": 2026,
        "trim": "Long Range",
        "body_type": "SUV",
        "price_new": 52000,
        "price_used_avg": 42000,
        "fuel_type": "electric",
        "mpg_city": 125,
        "mpg_highway": 115,
        "seating_capacity": 5,
        "cargo_cu_ft": 76.0,
        "towing_capacity_lbs": 3500,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 6.5,
        "turning_radius_ft": 19.0,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["autopilot", "heated_seats", "premium_audio"],
        "best_for": ["electric", "family", "commute"],
        "image_url": "https://example.com/modely.jpg"
    },
    {
        "id": "ford_mustang_mache_2026",
        "make": "Ford",
        "model": "Mustang Mach-E",
        "year": 2026,
        "trim": "Premium",
        "body_type": "SUV",
        "price_new": 54000,
        "price_used_avg": 43000,
        "fuel_type": "electric",
        "mpg_city": 110,
        "mpg_highway": 100,
        "seating_capacity": 5,
        "cargo_cu_ft": 59.7,
        "towing_capacity_lbs": 0,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 7,
        "ground_clearance_in": 6.8,
        "turning_radius_ft": 19.5,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["ford_co_pilot360", "b_o_sound", "panoramic_roof"],
        "best_for": ["electric", "performance"],
        "image_url": "https://example.com/mache.jpg"
    },
    {
        "id": "hyundai_ioniq5_2026",
        "make": "Hyundai",
        "model": "Ioniq 5",
        "year": 2026,
        "trim": "Limited",
        "body_type": "SUV",
        "price_new": 56000,
        "price_used_avg": 45000,
        "fuel_type": "electric",
        "mpg_city": 114,
        "mpg_highway": 98,
        "seating_capacity": 5,
        "cargo_cu_ft": 27.2,
        "towing_capacity_lbs": 2500,
        "drivetrain": "AWD",
        "safety_rating": 5,
        "reliability_score": 8,
        "ground_clearance_in": 6.9,
        "turning_radius_ft": 18.8,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": True,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": False,
        "key_features": ["hda2", "v2l", "augmented_reality_hud"],
        "best_for": ["electric", "technology"],
        "image_url": "https://example.com/ioniq5.jpg"
    },
    {
        "id": "mazda_mx5_2026",
        "make": "Mazda",
        "model": "MX-5 Miata",
        "year": 2026,
        "trim": "Grand Touring",
        "body_type": "convertible",
        "price_new": 35000,
        "price_used_avg": 28000,
        "fuel_type": "gas",
        "mpg_city": 26,
        "mpg_highway": 34,
        "seating_capacity": 2,
        "cargo_cu_ft": 4.6,
        "towing_capacity_lbs": 0,
        "drivetrain": "RWD",
        "safety_rating": 4,
        "reliability_score": 8,
        "ground_clearance_in": 5.1,
        "turning_radius_ft": 15.7,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": True,
        "is_manual_available": True,
        "key_features": ["bose_audio", "heated_seats", "led_lights"],
        "best_for": ["fun", "sportiness"],
        "image_url": "https://example.com/mx5.jpg"
    },
    {
        "id": "toyota_gr86_2026",
        "make": "Toyota",
        "model": "GR86",
        "year": 2026,
        "trim": "Premium",
        "body_type": "coupe",
        "price_new": 32000,
        "price_used_avg": 26000,
        "fuel_type": "gas",
        "mpg_city": 21,
        "mpg_highway": 28,
        "seating_capacity": 4,
        "cargo_cu_ft": 6.3,
        "towing_capacity_lbs": 0,
        "drivetrain": "RWD",
        "safety_rating": 4,
        "reliability_score": 8,
        "ground_clearance_in": 5.0,
        "turning_radius_ft": 16.1,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": True,
        "key_features": ["track_mode", "sport_exhaust", "aluminum_pedals"],
        "best_for": ["fun", "sportiness"],
        "image_url": "https://example.com/gr86.jpg"
    },
    {
        "id": "ford_mustang_2026",
        "make": "Ford",
        "model": "Mustang",
        "year": 2026,
        "trim": "GT Premium",
        "body_type": "coupe",
        "price_new": 48000,
        "price_used_avg": 38000,
        "fuel_type": "gas",
        "mpg_city": 15,
        "mpg_highway": 24,
        "seating_capacity": 4,
        "cargo_cu_ft": 13.5,
        "towing_capacity_lbs": 1000,
        "drivetrain": "RWD",
        "safety_rating": 4,
        "reliability_score": 7,
        "ground_clearance_in": 5.3,
        "turning_radius_ft": 17.9,
        "has_adaptive_cruise": True,
        "has_lane_keep": True,
        "has_parking_sensors": True,
        "has_rear_ac": False,
        "has_third_row": False,
        "has_roof_rack": False,
        "has_bed_liner": False,
        "is_convertible": False,
        "is_manual_available": True,
        "key_features": ["performance_package", "b_o_audio", "digital_dash"],
        "best_for": ["fun", "sportiness"],
        "image_url": "https://example.com/mustang.jpg"
    }
]

def get_car_by_id(car_id: str):
    for car in CARS:
        if car["id"] == car_id:
            return car
    return None

def get_all_cars():
    return CARS
